// Generated by CoffeeScript 1.7.1
var transformModel;

transformModel = function(inputModel) {
  var outputModel;
  outputModel = {
    classes: inputModel.classes.map(function(clazz) {
      var mappedClass;
      mappedClass = {
        name: clazz.name
      };
      mappedClass.attributes = clazz.attributes.map(function(attribute) {
        return ("" + attribute.name + " : " + attribute.type + " ") + [attribute.multiplicity && attribute.multiplicity[0] === "0" ? "[0..1]" : void 0];
      });
      return mappedClass;
    })
  };
  outputModel.associations = inputModel.associations.map(function(association) {
    var label;
    label = association.targetName ? " : " + association.targetName + " <" : (association.sourceName ? " : " + association.sourceName + " >" : "");
    return association.source + ' "' + association.sourceMultiplicity + '" -- "' + association.targetMultiplicity + '" ' + association.target + label;
  });
  inputModel.classes.filter(function(clazz) {
    return clazz.superType;
  }).forEach(function(clazz) {
    return outputModel.associations.push(clazz.superType + " <|-- " + clazz.name);
  });
  return outputModel;
};
